<style>
    .magazento-powered, .magazento-powered a {
    color: #888;
    font-size: 9px;
    text-align: right;
    text-decoration: none;
    margin: 0;
    }
</style>
<p class="magazento-powered">Powered by <a href="http://www.magazento.com/english/magento-ext/magazento-extensions" target="_blank">Magento extensions</a> - <a href="http://www.magazento.com/english/magento-ext/magazento-extensions/magento-one-step-page-checkout" target="_blank">Magento modules</a></p>