
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>



<body>
<div class="container">
	<div class="header">
    	<div class="logo"><img src="<?php echo $this->getSkinUrl() ?>images/logo.png" alt="Home" /></div>
        <div class="loginBox">
       	  <div class="topContact"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('header-phone-nr ')->toHtml() ?></div>
          <div class="topLogin"><a href="<?php echo $this->getUrl('customer/account')?>">Contul Meu</a><a href="<?php echo $this->getUrl('checkout/cart') ?>">Finalizare Comanda</a></div>
        </div>
        <div class="searchBox"><table width="100%" height="35" border="0" cellpadding="0" cellspacing="0">
          <tr>
            <td width="240">
            	<!--<p>Cosul meu: <span>100</span> buc / <span>2690.99 LEI</span></p>-->
            	<?php echo $this->getLayout()->createBlock('checkout/cart_sidebar')->setTemplate('checkout/cart/header_cart.phtml')->toHtml() ?>
            </td>
            <td>
            	<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalogsearch/form.mini.phtml')->toHtml(); ?>
            </td>
          </tr>
        </table>
        </div>
    </div>
    <div class="content">
        <?php echo $this->getChildHtml('header') ?>
        <div class="insidePageContent">
        	<div class="leftPart">
        		<?php echo $this->getChildHtml('left') ?>

            </div>
          <div class="contentPartINS">
             <?php echo $this->getChildHtml('content'); ?>
              <div class="clear"></div>
           </div>
            <div class="clear"></div>
        </div>
      <?php echo $this->getChildHtml('mainFooter') ?>
    </div>
</div>
</body>

</html>
